# references:
#   https://hub.docker.com/_/redis

version: "3.8"

services:
    redis:
        container_name: redis
        image: redis:7.0-alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        volumes:
            - redis_volume:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        hostname: redis
        networks:
            - redis-network
        command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --loglevel warning --requirepass AeYreOty

volumes:
    redis_volume:
        name: redis_volume
        driver: local

networks:
    redis-network:
        name: redis-network
        driver: bridge
