services:

    db:
        image: postgres:16.9-alpine
        container_name: postgres
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
            # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./scripts:/home/scripts
        ports:
            - 5432:5432
        hostname: postgres
        labels:
            - com.centurylinklabs.watchtower.enable="false"
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - postgres_network
        command:
            - "postgres"
            - "-c"
            - "shared_preload_libraries=pg_stat_statements"
            - "-c"
            - "compute_query_id=on"
            - "-c"
            - "pg_stat_statements.track=all"
            - "-c"
            - "pg_stat_statements.max=10000"
            - "-c"
            - "track_activity_query_size=2048"
            - "-c"
            - "log_checkpoints=on"
            - "-c"
            - "log_connections=on"
            - "-c"
            - "log_disconnections=on"
            - "-c"
            - "log_lock_waits=on"
            - "-c"
            - "log_temp_files=0"
            - "-c"
            - "log_min_duration_statement=0"
            - "-c"
            - "log_autovacuum_min_duration=0"
            - "-c"
            - "log_line_prefix='%t [%p]: [%l] %quser=%u,db=%d,app=%a,client=%h '"

volumes:
    postgres_data:
        name: postgres_data
        driver: local

networks:
    postgres_network:
        name: postgres_network
        driver: bridge
