
# references:
#   https://hub.docker.com/_/postgres
#   https://hub.docker.com/r/ankane/pghero
#   https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md

version: "3.7"

services:

    db:
        image: postgres:14.5-alpine
        container_name: postgres
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./scripts:/home/scripts
        ports:
            - 5432:5432
        hostname: postgres
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
        networks:
            - postgres_network
        command:
            - "postgres"
            - "-c"
            - "shared_preload_libraries=pg_stat_statements"
            - "-c"
            - "pg_stat_statements.track=all"
            - "-c"
            - "pg_stat_statements.max=10000"
            - "-c"
            - "track_activity_query_size=2048"

    db_stats:
        container_name: pghero
        image: ankane/pghero:v2.8.3
        restart: unless-stopped
        ports:
            - 35066:8080
        environment:
            DATABASE_URL: "postgres://postgres:1@postgres:5432/pedrozc90"
            PGHERO_USERNAME: pghero
            PGHERO_PASSWORD: pghero
        networks:
            - postgres_network
        depends_on:
            - db

volumes:
    postgres_data:
        name: postgres_data
        driver: local

networks:
    postgres_network:
        name: postgres_network
        driver: bridge
