services:
    db:
        image: postgres:16-alpine
        container_name: postgres
        hostname: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres.conf:/etc/postgresql/postgresql.conf:ro # configuration file
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro # initialization script
        labels:
            - com.centurylinklabs.watchtower.enable="false"
        networks:
            - postgres_network
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready --username postgres --dbname postgres" ]
        deploy:
            resources:
                limits:
                    cpus: "4.0"     # limit to 4 CPU cores
                    memory: "4GB"   # limit to 4 GB RAM
                reservations:
                    cpus: "1.0"     # reserve 1 CPU core
                    memory: "512M"  # reserve 512 MB RAM
        logging:
            driver: "json-file"
            options:
                max-size: "10m" # limit log file size to 10 mb
                max-file: "5"   # keep maximum 3 log files
        command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]

volumes:
    postgres_data:
        name: postgres_data
        driver: local

networks:
    postgres_network:
        name: postgres_network
        driver: bridge
