version: "3.8"

services:
    minio:
        image: minio/minio:latest
        container_name: minio
        hostname: minio
        restart: unless-stopped
        ports:
            - "9000:9000"   # S3 API port
            - "9001:9001"   # MinIO Consile UI
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/ready"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    minio_data:
        name: minio_data
        driver: local

networks:
    minio_network:
        name: minio_network
        driver: bridge
