local function band(a,b)
	return(a & b)
end

local function bor(a,b)
	return (a | b)
end

local function lshift(a,b)
	return (a << b)
end

local COMBATLOG_OBJECT_AFFILIATION_MINE = 1
local COMBATLOG_OBJECT_AFFILIATION_PARTY = 2
local COMBATLOG_OBJECT_AFFILIATION_RAID = 4
local COMBATLOG_OBJECT_AFFILIATION_OUTSIDER = 8
local COMBATLOG_OBJECT_AFFILIATION_MASK = 15
local COMBATLOG_OBJECT_REACTION_FRIENDLY = 16
local COMBATLOG_OBJECT_REACTION_NEUTRAL = 32
local COMBATLOG_OBJECT_REACTION_HOSTILE = 64
local COMBATLOG_OBJECT_REACTION_MASK = 240
local COMBATLOG_OBJECT_CONTROL_PLAYER = 256
local COMBATLOG_OBJECT_CONTROL_NPC = 512
local COMBATLOG_OBJECT_CONTROL_MASK = 768
local COMBATLOG_OBJECT_TYPE_PLAYER = 1024
local COMBATLOG_OBJECT_TYPE_NPC = 2048
local COMBATLOG_OBJECT_TYPE_PET = 4096
local COMBATLOG_OBJECT_TYPE_GUARDIAN = 8192
local COMBATLOG_OBJECT_TYPE_OBJECT = 16384
local COMBATLOG_OBJECT_TYPE_MASK = 64512
local COMBATLOG_OBJECT_TARGET = 65536
local COMBATLOG_OBJECT_FOCUS = 131072
local COMBATLOG_OBJECT_MAINTANK = 262144
local COMBATLOG_OBJECT_MAINASSIST = 524288
local COMBATLOG_OBJECT_NONE = 2147483648
local COMBATLOG_OBJECT_SPECIAL_MASK = 4294901760

-- local Void_Tendril = 2600
-- local Spirit_Drain_Totem = 8776
local flag = 2600

print("FLAG", flag)
print("COMBATLOG_OBJECT_AFFILIATION_MINE", band(flag, COMBATLOG_OBJECT_AFFILIATION_MINE));
print("COMBATLOG_OBJECT_AFFILIATION_PARTY", band(flag, COMBATLOG_OBJECT_AFFILIATION_PARTY));
print("COMBATLOG_OBJECT_AFFILIATION_RAID", band(flag, COMBATLOG_OBJECT_AFFILIATION_RAID));
print("COMBATLOG_OBJECT_AFFILIATION_OUTSIDER", band(flag, COMBATLOG_OBJECT_AFFILIATION_OUTSIDER));
print("COMBATLOG_OBJECT_AFFILIATION_MASK", band(flag, COMBATLOG_OBJECT_AFFILIATION_MASK));
print("COMBATLOG_OBJECT_REACTION_FRIENDLY", band(flag, COMBATLOG_OBJECT_REACTION_FRIENDLY));
print("COMBATLOG_OBJECT_REACTION_NEUTRAL", band(flag, COMBATLOG_OBJECT_REACTION_NEUTRAL));
print("COMBATLOG_OBJECT_REACTION_HOSTILE", band(flag, COMBATLOG_OBJECT_REACTION_HOSTILE));
print("COMBATLOG_OBJECT_REACTION_MASK", band(flag, COMBATLOG_OBJECT_REACTION_MASK));
print("COMBATLOG_OBJECT_CONTROL_PLAYER", band(flag, COMBATLOG_OBJECT_CONTROL_PLAYER));
print("COMBATLOG_OBJECT_CONTROL_NPC", band(flag, COMBATLOG_OBJECT_CONTROL_NPC));
print("COMBATLOG_OBJECT_CONTROL_MASK", band(flag, COMBATLOG_OBJECT_CONTROL_MASK));
print("COMBATLOG_OBJECT_TYPE_PLAYER", band(flag, COMBATLOG_OBJECT_TYPE_PLAYER));
print("COMBATLOG_OBJECT_TYPE_NPC", band(flag, COMBATLOG_OBJECT_TYPE_NPC));
print("COMBATLOG_OBJECT_TYPE_PET", band(flag, COMBATLOG_OBJECT_TYPE_PET));
print("COMBATLOG_OBJECT_TYPE_GUARDIAN", band(flag, COMBATLOG_OBJECT_TYPE_GUARDIAN));
print("COMBATLOG_OBJECT_TYPE_OBJECT", band(flag, COMBATLOG_OBJECT_TYPE_OBJECT));
print("COMBATLOG_OBJECT_TYPE_MASK", band(flag, COMBATLOG_OBJECT_TYPE_MASK));
print("COMBATLOG_OBJECT_TARGET", band(flag, COMBATLOG_OBJECT_TARGET));
print("COMBATLOG_OBJECT_FOCUS", band(flag, COMBATLOG_OBJECT_FOCUS));
print("COMBATLOG_OBJECT_MAINTANK", band(flag, COMBATLOG_OBJECT_MAINTANK));
print("COMBATLOG_OBJECT_MAINASSIST", band(flag, COMBATLOG_OBJECT_MAINASSIST));
print("COMBATLOG_OBJECT_NONE", band(flag, COMBATLOG_OBJECT_NONE));
print("COMBATLOG_OBJECT_SPECIAL_MASK", band(flag, COMBATLOG_OBJECT_SPECIAL_MASK));