version: "3.9"

services:

    rabbitmq:
        build:
            context: .
            dockerfile: Dockerfile
        image: rabbitmq:1.0.0
        container_name: rabbitmq
        hostname: rabbitmq
        restart: unless-stopped
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - rabbitmq-volume:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: pedrozc90
            RABBITMQ_DEFAULT_PASS: AeYreOty
            RABBITMQ_DEFAULT_VHOST: master
        networks:
            - rabbitmq-network

volumes:
    rabbitmq-volume:
        name: rabbitmq-volume
        driver: local

networks:
    rabbitmq-network:
        name: rabbitmq-network
        driver: bridge
